version: '2'
services:
  applications:
    image: tianon/true
    volumes:
      - ../Clients/project-1/:/var/www/project-1

  apache2:
    build:
      context: ./apache2
      dockerfile: Dockerfile
    volumes_from:
      - applications
    volumes:
      - ./logs/apache2:/var/log/apache2
      - ./apache2/sites-enabled:/etc/apache2/sites-enabled
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes_from:
      - applications
    volumes:
      - ./logs/mysql:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: my-application
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root

volumes:
  apache2:
    driver: "local"
  mysql:
    driver: "local"
